Metrics implementation for MasterDataIndexerJob
Sanketika-Obsrv/obsrv-core pull request #55
Opened 2023-12-26 11:33 UTC by SurabhiAngadi

Changes -

1. Updated job to work with service account.
2. Job compatible for multiple cloud storage provider.
3. Added metrics for the job.
4. Sample metric event ->
{
"eid": "METRIC",
"ets": 1700474870038,
"mid": "b7e57824-baa9-4eb2-b452-00b1c74abd84",
"actor": {
"id": "MasterDataProcessorIndexerJob",
"type": "SYSTEM"
},
"context": {
"env": "local",
"pdata": {
"id": "DataProducts",
"pid": "MasterDataProcessorIndexerJob",
"ver": "1.0.0"
}
},
"object": {
"id": "telemetry-content-data",
"type": "Dataset",
"ver": "1.0.0"
},
"edata": {
"metric": {
"metric_name": 1,
"total_time_taken": 34977,
"total_events_processed": 10000, ...etc.
},
"labels": [
{
"key": "job",
"value": "MasterDataIndexer"
},
{
"key": "datasetId",
"value": "telemetry-content-data"
},
{
"key": "cloud",
"value": "aws"
}
]
}
}

Test scenarios to be performed -

1. Job should filter dataset based on indexData column and check if there are more than one datasource associated with each dataset. If so, return early.
2. Job should create data file and upload to respective cloud storage provider.
3. Submit ingestion spec to druid for processing.
4. Update datasourceRef if needed.
5. Job should generate metrics for both success and failure scenarios.

2024-01-04 13:19 UTC, SanthoshVasabhaktula requested changes

2024-01-04 13:19 UTC, SanthoshVasabhaktula commented on data-products/src/main/scala/org/sunbird/obsrv/dataproducts/MasterDataProcessorIndexer.scala
> +      logger.debug("Checking dataset status for id - " + dataset.id)
Remove debug statement

2024-01-04 13:19 UTC, SanthoshVasabhaktula commented on data-products/src/main/scala/org/sunbird/obsrv/dataproducts/helper/BaseMetricHelper.scala
> +    val metric = JobMetric(ets = new DateTime(DateTimeZone.UTC).getMillis, actor = actor, context = context, `object` = `object`, edata = edata)
System.currentMillis() is enough. Not need to create new datetime objects unecessarily

2024-01-04 13:19 UTC, SanthoshVasabhaktula commented on data-products/src/main/scala/org/sunbird/obsrv/dataproducts/util/CommonUtil.scala
> +  // $SCOVERAGE-ON$
Code can be covered

2024-01-04 13:19 UTC, SanthoshVasabhaktula commented on dataset-registry/src/main/scala/org/sunbird/obsrv/model/DatasetModels.scala
> +  val Draft, Publish, Live, Retired, Purged, ACTIVE = Value
Revert the change. There is no status called ACTIVE. It is Live

2024-01-04 13:19 UTC, SanthoshVasabhaktula commented on framework/src/main/scala/org/sunbird/obsrv/core/util/PostgresConnect.scala
> +
Reset the file

2024-01-19 08:54 UTC, SanthoshVasabhaktula requested changes

2024-01-19 08:54 UTC, SanthoshVasabhaktula commented on data-products/src/main/scala/org/sunbird/obsrv/dataproducts/util/StorageUtil.scala
> +    }
Why is there a check specific for azure?

2024-01-19 08:54 UTC, SanthoshVasabhaktula commented on data-products/src/main/scala/org/sunbird/obsrv/dataproducts/util/StorageUtil.scala
> +    else config.getString("cloud_input_source_spec").replace("FILE_PATH", filePath)
Incorrect equals comparison
Remove the local file check

2024-01-19 08:54 UTC, SanthoshVasabhaktula commented on data-products/src/main/resources/masterdata-indexer.conf
> +cloud_input_source_spec="{\"spec\":{\"ioConfig\":{\"type\":\"index_parallel\",\"inputSource\":{\"type\":\"${cloudStorage.provider}\",\"objectGlob\":\"**.json.gz\",\"prefixes\":[\"FILE_PATH\"]}}}}"
Remove variable specific to local

2024-01-23 06:41 UTC, manjudr approved these changes

2024-01-23 06:41 UTC, manjudr commented
The changes are looks fine.

2024-01-23 06:42 UTC, merged